## Konvolucija

In [1]:
def showImage(name,img):
    cv2.imshow(name,img)
    

import cv2
import matplotlib.pyplot as plt
import numpy as np

#Orig. slika
img = cv2.imread("lenna.png",0) 
original = img

showImage("SLika", img)
cv2.waitKey()
#Jedro

for j in range(1,15):
    kernel = np.ones((3,3), np.int8)/(9)
    print(kernel)
    #Konvolucija: slika, globina, jedro, sidranje
    filtered = cv2.filter2D(img,-1,kernel, anchor=(-1,-1))
 
    compare = cv2.hconcat((original,filtered))
    img = filtered

    showImage("Primerjava original in filtrirana slike z nizkim sitom "+str(2*j+1) + " krat", compare)
    cv2.waitKey()
    cv2.destroyAllWindows()

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.11111111 0.1111

In [39]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

#Orig. slika
img = cv2.imread("lenna.png",0) 
img1 = img
#Jedro

for j in range(1,15):
    kernel = np.ones((2*j+1,2*j+1), np.int8)/((2*j+1)*(2*j+1))
    print(kernel)
    #Konvolucija: slika, globina, jedro, sidranje
    filtered = cv2.filter2D(img,-1,kernel, anchor=(-1,-1))   
    compare = cv2.hconcat((img,filtered))

    showImage("Primerjava original in filtrirana slika s filtrom reda "+str(2*j+1), compare)
    cv2.waitKey()
    cv2.destroyAllWindows()

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
[[0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]
 [0.02040816 0.02040816 0.02040816 0.02040816 0.02040816 0.02040816
  0.02040816]]
[[0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
  0.01234568 0.01234568 0.01234568]
 [0.01234568 0.01234568 0.01234568 0.01234568 0.01234568 0.01234568
  0

[[0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008]
 [0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008]
 [0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008]
 [0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008]
 [0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.00277008
  0.00277008 0.00277008 0.00277008 0.00277008 0.00277008 0.0

[[0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036]
 [0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036]
 [0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036]
 [0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.00189036 0.00189036 0.00189036 0.00189036 0.00189036 0.00189036
  0.001890

[[0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174]
 [0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174]
 [0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.00137174 0.00137174 0.00137174]
 [0.00137174 0.00137174 0.00137174 0.00137174 0.00137174 0.00137174
  0.0013

[[0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906]
 [0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906]
 [0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906 0.00118906
  0.00118906 0.00118906 0.00118906 0.00118906 0.00118906]
 [0.001189

## Filtri

In [3]:
#Gauss

import cv2
import matplotlib.pyplot as plt
import numpy as np

def showImage(name,img):
    cv2.imshow(name,img)

#Gaussov filter
img = cv2.imread("lenna.png",0) 

gauss = cv2.GaussianBlur(img,(15,15),0)
compare = cv2.hconcat((img,gauss))
showImage("Img vs. gauss filtered", compare)

cv2.waitKey()
cv2.destroyAllWindows()


ModuleNotFoundError: No module named 'cv2'

## Šum in odstranjevanje šuma

In [4]:

#Dodajmo v sliko šum
img = cv2.imread("lenna.png",0)

#Gaussov šum
gauss_noise = np.random.normal(0,1,img.shape).astype(np.uint8) #Igrajte se z drugim parametrom pri ustvarjanju šuma
noisy = img | gauss_noise

medianFiltered = cv2.medianBlur(noisy,5) #velikost jedra (igrajte se tudi s tem parametrom)

compare = cv2.hconcat((noisy,medianFiltered))
showImage("Noisy vs. median filtered", compare)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
img = cv2.imread("sol-poper.png",0)
filtered = cv2.medianBlur(img,5) 

compare = cv2.hconcat((img,filtered))
showImage("Noisy vs. median filtered", compare)
cv2.waitKey()
cv2.destroyAllWindows()


## Sobel

In [2]:

img = cv2.imread("lenna.png",0) 

gamma = 0
sy = cv2.Sobel(img,-1,0,1,3)
sx = cv2.Sobel(img,-1,1,0,3)

sx = np.uint8(np.absolute(sx))
sy = np.uint8(np.absolute(sy))

gauss_amplituda = cv2.addWeighted(sx,0.5, sy,0.5,gamma)
compare = cv2.hconcat((sx,sy))
showImage("Sx vs Sy", compare)

cv2.imshow("Amplituda Sx + Sy", gauss_amplituda)
cv2.waitKey()
cv2.destroyAllWindows()

## Pazite na podatkovni tip oz. predznak

In [10]:
whiteSquare = np.zeros((512,512), np.uint8)
whiteSquare[100:400,200:300] = 255
showImage("Beli kvadrat", whiteSquare)
cv2.waitKey()
sx = cv2.Sobel(whiteSquare,cv2.CV_64F,1,0,3)
showImage("Napacni robovi", sx)
cv2.waitKey()
showImage("Pravilni robovi", np.absolute(sx))

cv2.waitKey()
cv2.destroyAllWindows()

## Roberts cross

In [4]:
import cv2
import numpy as np
img = cv2.imread("lenna.png",0)
r1 = np.array([[1,0],[0,-1]])
r2 = np.array([[0,1],[-1,0]])


r1o = cv2.filter2D(img,-1,r1)
r2o = cv2.filter2D(img,-1,r2)

roberts_odvoda = cv2.hconcat((r1o,r2o))

#roberts_amplituda = np.sqrt(r1o**2 + r2o**2)
gamma = 0

roberts_amplituda = cv2.addWeighted(np.absolute(r1o),0.5, np.absolute(r2o),0.5,gamma)
cv2.imshow("Roberts Odvoda", roberts_odvoda)
cv2.imshow("Roberts Gradienti", (roberts_amplituda))
cv2.waitKey()
cv2.destroyAllWindows()




## Prewitt

In [9]:
import cv2
import numpy as np
img = cv2.imread("lenna.png",0)
r1 = np.array([[1,0, -1],[1, 0,-1], [1,0,-1]])


r2 = np.array([[1,1,1],[0,0,0], [-1,-1,-1]])
p1o = cv2.filter2D(img,-1,r1)
p2o = cv2.filter2D(img,-1,r2)

prewitt_odvoda = cv2.hconcat((p1o,p2o))
gamma = 1

prewitt_amplituda = cv2.addWeighted(np.absolute(p1o),0.5, np.absolute(p2o),0.5,gamma)
cv2.imshow("Prewitt Odvoda", prewitt_odvoda)
cv2.imshow("Prewitt Gradienti", (prewitt_amplituda))
cv2.waitKey()
cv2.destroyAllWindows()


## Igranje z robovi


In [11]:
import cv2
import numpy as np
global sLow, sHigh
sLow = 10
sHigh = 100
def readLowTh(val):
    global sLow
    sLow = val
    #print(val)
def readHighTh(val):
    global sHigh
    sHigh = val
    #print(val)

def detectEdge(img):
    global sLow, sHigh
    img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)      
    return cv2.Canny(img, sLow, sHigh)

def effect(frame,edge):
    eff = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    indices = np.where(edge>0)
    eff[indices[0],indices[1],1] = 255                
    return cv2.cvtColor(eff,cv2.COLOR_HSV2BGR)

    
def openCamera():    
    cap = cv2.VideoCapture(0)
    if cap.isOpened() == False:
        print("Ne morem odpreti kamere")
    
    cv2.namedWindow("Kamera-original")
    cv2.namedWindow("Kamera-edges")
    cv2.namedWindow("Kamera-effect")
    while True:
        ret, frame = cap.read()
        frame = cv2.flip(frame,1)
        if ret == True: 
            edge = detectEdge(frame)
            cv2.imshow("Kamera-original",frame)
            cv2.imshow("Kamera-edges",edge)
        
            cv2.imshow("Kamera-effect",effect(frame,edge))
            if cv2.waitKey(10) & 0xFF == ord('q'):
                break
        else:   
            break
    cap.release()
    cv2.destroyAllWindows()
img = cv2.imread("lenna.png")
cv2.namedWindow("Control")
cv2.createTrackbar("Low threshold","Control",0,255,readLowTh)
cv2.createTrackbar("High threshold","Control",0,255,readHighTh)

openCamera()